config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins, path: 'admins'
  devise_for :users, path: 'users', controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'blogs#index'

  namespace :admin do
    resources :blogs
    get '/', to: 'blogs#home'
  end

  resources :blogs, only: [:show, :index]
  resources :users, only: [:show, :update, :edit]
  resources :reacts, only: :create
  delete 'reacts', to: 'reacts#destroy'
  patch 'reacts', to: 'reacts#update'
  get 'messages/index'
  get 'blogs/:id/:token', to: 'blogs#show', as: 'token_blog'
  get 'app_author', to: 'blogs#app_author'
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :reacts, dependent: :destroy
  enum category: %w[family school study]

  mount_uploader :image, ImageUploader
  mount_uploader :author_picture, AuthorPictureUploader

  ATTR_PARAMS = [
    :title,
    :category,
    :public_time,
    :is_public,
    :is_recommend,
    :image,
    :body,
    :author_name,
    :author_position,
    :author_age,
    :author_picture
  ].freeze

  validates :title, presence: true, length: { maximum: 255 }
  validates :category, presence: true
  validates :public_time, presence: true
  validates :body, presence: true
  validates :image, presence: true
  validates :author_name, presence: true
  validates :author_position, presence: true
  validates :author_age, presence: true
  validates :author_picture, presence: true

  validate :validate_image_size
  validate :validate_author_age

  scope :sort_blog, ->(param_sort) { order public_time: param_sort }
  scope :public_blogs, lambda {
    where 'is_public = ? AND public_time < ?', true, Time.zone.now
  }
  scope :recommend_blogs, -> { where 'is_recommend = ?', true }
  scope :blog_by_category, ->(category) { where 'category = ?', category }

  class << self
    def new_token
      chars = (0..9).to_a + ('a'..'z').to_a + ('A'..'Z').to_a
      chars.sample(16).join
    end
  end

  private

  def validate_image_size
    return unless image.size > Settings.image.max_capacity.megabytes
    errors.add :image,
               I18n.t('error_capacity_image',
                      maximum: Settings.image.max_capacity)
  end

  def validate_author_age
    return errors.add I18n.t('error_age') if author_age < 0
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  before_action :authenticate_admin!
  before_action :load_blog, only: [:update, :edit]
  before_action :load_blogs, only: :index

  def index
    respond_to do |format|
      if request.xhr?
        sort_blog
        format.html do
          render partial: 'sort_blog',
                 locals: { sort_blogs: @sort_blogs }
        end
      end
      format.html
    end
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new create_blog_params
    default_author_picture if @blog.author_picture.blank?
    if @blog.save
      flash[:success] = t '.saved'
      redirect_to admin_blogs_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if request.xhr?
      render json: @blog.is_public
      update_params
    else
      update_blog
    end
  end

  def home; end

  private

  def load_blogs
    @search = Blog.ransack params[:q]
    @blogs = @search.result.order(created_at: :desc).page(params[:page])
                    .per Settings.list_blog
  end

  def sort_blog
    params[:sort] ||= :DESC
    @sort_blogs = Blog.sort_blog(params[:sort]).page(params[:page])
                      .per Settings.list_blog
  end

  def update_params
    if params[:public_time].present?
      @blog.update_attributes public_time: params[:public_time]
    elsif params[:is_public].present?
      @blog.update_attributes is_public: params[:is_public]
    end
  end

  def blog_params
    params.require(:blog).permit Blog::ATTR_PARAMS
  end

  def create_blog_params
    blog_params.merge! token: Blog.new_token
  end

  def update_blog
    if @blog.update_attributes blog_params
      flash[:success] = t '.updated'
      redirect_to admin_blogs_path
    else
      render :edit
    end
  end

  def load_blog
    @blog = Blog.find_by id: params[:id]
  end

  def default_author_picture
    path = File.join(Rails.root, 'app/assets/images/', Settings.author.image)
    File.open(path) do |f|
      @blog.author_picture = f
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :check_token, only: :show
  before_action :load_react, only: [:show, :index]

  def index
    @blogs = Blog.public_blogs.order(public_time: :desc).page(params[:page]).per 5
    @recommend_blogs = Blog.recommend_blogs.order(public_time: :desc).page(params[:page]).per 5
    @category_blogs = Blog.blog_by_category(params[:category_type])
                          .order(public_time: :desc).page(params[:page]).per 5
    respond_to do |format|
      format.html
      format.js
      return unless request.xhr?
      format.json { data_json }
    end
  end

  def show
    respond_to do |format|
      if request.xhr?
        format.html do
          render partial: 'author',
                 locals: { blog: @blog }
        end
      end
      format.html
    end
  end

  def app_author; end

  private

  def load_react
    @react = if current_user.present?
               React.find_by_user_id_and_blog_id(current_user.id, params[:id])
             else
               React.find_by_code_and_blog_id(cookies[:guest_token], params[:id])
             end
  end

  def data_json
    render json: {
      category_blogs: render_to_string(
        partial: 'blogs/category_blogs',
        locals: { category_blogs: @category_blogs },
        formats: 'html',
        layout: false
      ),
      recommend_blogs: render_to_string(
        partial: 'blogs/recommend_blogs',
        locals: { recommend_blogs: @recommend_blogs },
        formats: 'html',
        layout: false
      )
    }
  end

  def check_token
    if params[:token].present?
      @blog = Blog.find_by(token: params[:token], id: params[:id])
    else
      authenticate_user!
      @blog = Blog.find_by id: params[:id]
    end
  end
end

app/views/blogs/_author.html.erb
<div class="author-header">
  <%= image_tag "back.png", size: Settings.author.back_button,
    class: "back-button go-back" %>
  <p class="author-header-title"><%= t ".author" %></p>
</div>
<div class="author-information">
  <%= image_tag blog.author_picture, class: "author-ava" %>
  <div class="information">
    <%= image_tag "author1.png", class: "info-author" %>
    <div class="text-under-image">
      <div class="row show-author-info">
        <div class="picture-author">
          <%= image_tag "name.png", class: "border-button" %>
        </div>
        <div class="text-author">
          <%= blog.author_name %>
        </div>
      </div>
      <div class="row show-author-info">
        <div class="picture-author">
          <%= image_tag "age.png", class: "border-button" %>
        </div>
        <div class=" text-author">
          <%= blog.author_age %>
        </div>
      </div>
      <div class="row show-author-info">
        <div class="picture-author">
          <%= image_tag "position.png", class: "border-button" %>
        </div>
        <div class="text-author">
          <%= blog.author_position %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="fix-info">
  <%= image_tag "author-properties.png", class: "border-button" %>
</div>

app/views/blogs/_blog_list.html.erb
<div class="row blog-list-title">
  <p class="user-list-title">
    <%= link_to blog.title, blog_path(blog), data: {turbolinks: false} %>
  </p>
</div>
<div class="row">
  <div class="category-public">
    <span class="user-list-category" id="<%= blog.category %>">
      <%= t ".#{blog.category}" %>
    </span>
    <span class="user-list-public-time">
      <%= format_time(blog.public_time, :format_date_show) %>
    </span>
  </div>
  <div class="count-react">
    <span class="emotion-count">
      <%= image_tag "icon1.png", size: Settings.blog.icon_vote %>
      <span class="count-love">
        <%= blog.reacts.count_vote(0).size %>
      </span>
    </span>
    <span class="emotion-count">
      <%= image_tag "icon2.png", size: Settings.blog.icon_vote %>
      <span class="count-like">
        <%= blog.reacts.count_vote(1).size %>
      </span>
    </span>
    <span class="emotion-count">
      <%= image_tag "icon3.png", size: Settings.blog.icon_vote %>
      <span class="count-sad">
        <%= blog.reacts.count_vote(2).size %>
      </span>
    </span>
    <span class="emotion-count">
      <%= image_tag "icon4.png", size: Settings.blog.icon_vote %>
      <span class="count-sorrow">
        <%= blog.reacts.count_vote(3).size %>
      </span>
    </span>
  </div>
</div>

app/views/blogs/_blogs.html.erb
<% @blogs.each do |blog| %>
  <div class="blog-in-list">
    <% if blog.is_recommend? %>
      <%= image_tag "commend.png", size: Settings.blog.recommend_icon %>
      <div class="row1 blog-recommend">
        <%= render "blog_list", blog: blog %>
      </div>
    <% else %>
      <div class="row1">
        <%= render "blog_list", blog: blog %>
      </div>
    <% end %>
  </div>
  <div class="divider"></div>
<% end %>

app/views/blogs/_category_blogs.html.erb
<div id="my-blogs">
  <% category_blogs.each do |category_blog| %>
    <div class="blog-in-list">
      <% if category_blog.is_recommend? %>
        <%= image_tag "commend.png", size: Settings.blog.recommend_icon %>
        <div class="row1 blog-recommend">
          <%= render "blog_list", blog: category_blog %>
        </div>
      <% else %>
        <div class="row1">
          <%= render "blog_list", blog: category_blog %>
        </div>
      <% end %>
    </div>
    <div class="divider"></div>
  <% end %>
  <div id="infinite-scrolling">
    <%= paginate category_blogs, theme: "twitter-bootstrap-3" %>
  </div>
</div>

app/views/blogs/_modal.html.erb
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="image-modal">
      <%= image_tag "modal.png" %>
    </div>
    <div class="button-modal">
      <%= link_to image_tag("modal-button1.png"), "javascrip:void(0)",
        data: {dismiss: "modal"} %>
      <%= link_to image_tag("modal-button2.png"), app_author_path %>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $('#myModal').modal();
</script>

app/views/blogs/_react.html.erb
<div id="react-form">
  <div class="react-title">
    <%= image_tag "title-react.png", class: "title-react" %>
  </div>
  <div class="button-form">
    <div class="react-button">
      <% if react.present? && react.love? %>
        <div class="loved" value="love">
          <%= image_tag "voted.png", class: "emotion" %>
          <%= image_tag "voted-button.png", class: "border-button" %>
          <p class="text-emotion text-voted"><%= t ".love" %></p>
        </div>
        <div class="no-love hidden-input">
          <%= image_tag "emo1.png", class: "emotion" %>
          <%= image_tag "border-button.png", class: "border-button" %>
          <p class="text-emotion"><%= t ".love" %></p>
        </div>
      <% else %>
        <div class="no-love">
          <%= image_tag "emo1.png", class: "emotion" %>
          <%= image_tag "border-button.png", class: "border-button" %>
          <p class="text-emotion"><%= t ".love" %></p>
        </div>
        <div class="loved hidden-input" value="love">
          <%= image_tag "voted.png", class: "emotion" %>
          <%= image_tag "voted-button.png", class: "border-button" %>
          <p class="text-emotion text-voted"><%= t ".love" %></p>
        </div>
      <% end %>
    </div>
    <div class="react-button">
      <% if react.present? && react.like? %>
        <div class="liked" value="like">
          <%= image_tag "voted.png", class: "emotion" %>
          <%= image_tag "voted-button.png", class: "border-button" %>
          <p class="text-emotion text-voted"><%= t ".like" %></p>
        </div>
        <div class="no-like hidden-input">
          <%= image_tag "emo2.png", class: "emotion" %>
          <%= image_tag "border-button.png", class: "border-button" %>
          <p class="text-emotion"><%= t ".like" %></p>
        </div>
      <% else %>
        <div class="no-like">
          <%= image_tag "emo2.png", class: "emotion" %>
          <%= image_tag "border-button.png", class: "border-button" %>
          <p class="text-emotion"><%= t ".like" %></p>
        </div>
        <div class="liked hidden-input" value="like">
          <%= image_tag "voted.png", class: "emotion" %>
          <%= image_tag "voted-button.png", class: "border-button" %>
          <p class="text-emotion text-voted"><%= t ".like" %></p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="form-button">
    <div class="react-button">
      <% if react.present? && react.sad? %>
        <div class="sad" value="sad">
          <%= image_tag "voted.png", class: "emotion" %>
          <%= image_tag "voted-button.png", class: "border-button" %>
          <p class="text-emotion text-voted"><%= t ".sad" %></p>
        </div>
        <div class="no-sad hidden-input">
          <%= image_tag "emo3.png", class: "emotion" %>
          <%= image_tag "border-button.png", class: "border-button" %>
          <p class="text-emotion"><%= t ".sad" %></p>
        </div>
      <% else %>
        <div class="sad hidden-input" value="sad">
          <%= image_tag "voted.png", class: "emotion" %>
          <%= image_tag "voted-button.png", class: "border-button" %>
          <p class="text-emotion text-voted"><%= t ".sad" %></p>
        </div>
        <div class="no-sad">
          <%= image_tag "emo3.png", class: "emotion" %>
          <%= image_tag "border-button.png", class: "border-button" %>
          <p class="text-emotion"><%= t ".sad" %></p>
        </div>
      <% end %>
    </div>
    <div class="react-button">
      <% if react.present? && react.sorrow? %>
        <div class="sorrow" value="sorrow">
          <%= image_tag "voted.png", class: "emotion" %>
          <%= image_tag "voted-button.png", class: "border-button" %>
          <p class="text-emotion text-voted"><%= t ".sorrow" %></p>
        </div>
        <div class="no-sorrow hidden-input">
          <%= image_tag "emo4.png", class: "emotion" %>
          <%= image_tag "border-button.png", class: "border-button" %>
          <p class="text-emotion"><%= t ".sorrow" %></p>
        </div>
      <% else %>
        <div class="sorrow hidden-input" value="sorrow">
          <%= image_tag "voted.png", class: "emotion" %>
          <%= image_tag "voted-button.png", class: "border-button" %>
          <p class="text-emotion text-voted"><%= t ".sorrow" %></p>
        </div>
        <div class="no-sorrow">
          <%= image_tag "emo4.png", class: "emotion" %>
          <%= image_tag "border-button.png", class: "border-button" %>
          <p class="text-emotion"><%= t ".sorrow" %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>
<input type="hidden" value="<%= blog.id %>" class="blog-id"></input>
<% if current_user.present? %>
  <input type="hidden" value="<%= current_user.id %>" class="user-id"></input>
<% end %>

app/views/blogs/_recommend_blogs.html.erb
<div id="my-blogs">
  <% recommend_blogs.each do |recommend_blog| %>
    <div class="blog-in-list">
      <%= image_tag "commend.png", size: Settings.blog.recommend_icon %>
      <div class="row1 blog-recommend">
        <%= render "blog_list", blog: recommend_blog %>
      </div>
    </div>
    <div class="divider"></div>
  <% end %>
  <div id="infinite-scrolling">
    <%= paginate recommend_blogs, theme: "twitter-bootstrap-3" %>
  </div>
</div>

app/views/blogs/_social_share_button.html.erb
<div class="social-share-button">
  <%= link_to (image_tag Settings.share.twitter),
    "https://twitter.com/intent/tweet?url=http://localhost:3000/blogs/#{blog.id}/#{blog.token}&text=#{blog.title}",
    class: "icon-share" %>
  <%= link_to (image_tag Settings.share.facebook),
    'https://www.facebook.com/sharer.php?u=http://localhost:3000/blogs/#{blog.id}/#{blog.token}&text=#{blog.title}',
    class: "icon-share" %>
  <%= link_to (image_tag Settings.share.line),
    "https://lineit.line.me/share/ui?url=http://localhost:3000/blogs/#{blog.id}/#{blog.token}&text=#{blog.title}",
    class: "icon-share" %>
</div>

app/views/blogs/_tab_bar.html.erb
<nav class="navbar navbar-fixed-bottom tab-bar">
  <div class="container-fluid" id="tab-bar-container">
    <ul class="nav navbar-nav text-center">
      <li class="tab-message">
        <%= link_to messages_index_path do %>
          <%= image_tag "tab-bar1.png", class: "tab-message-show" %>
          <%= image_tag "tab-active1.png", class: "tab-message-active" %>
        <% end %>
      </li>
      <li class="tab-index">
        <%= link_to blogs_path, data: {turbolinks: false} do %>
          <%= image_tag "tab-bar2.png", class: "tab-index-show" %>
          <%= image_tag "tab-active2.png", class: "tab-index-active" %>
        <% end %>
      </li>
      <li class="tab-profile">
        <% if current_user.present? %>
          <%= link_to user_path(current_user) do %>
            <%= image_tag "tab-bar3.png", class: "tab-profile-show" %>
            <%= image_tag "tab-active3.png", class: "tab-profile-active" %>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <%= image_tag "login.png" %>
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/blogs/app_author.html.erb
<div class="app-author-header">
  <%= link_to image_tag("back.png", size: Settings.author.back_button),
    root_path, class: "go-back button-back" %>
  <p class="author-header-title app-author-title">
    <%= t "blogs.author.author" %>
  </p>
</div>
<div class="app_author">
  <%= image_tag "app_author.png" %>
</div>

app/views/blogs/index.html.erb
<div class="fix-top">
  <div class="author-header">
    <p class="author-header-title"><%= t ".list" %></p>
  </div>
  <div id="my-div" class="menu-index">
    <div id="my-content">
      <ul class="nav nav-tabs" id="menu-list">
        <li class="active">
          <a href="#home" data-toggle="tab" value="home"
            id="tab-home">
            <%= t ".home" %>
          </a>
        </li>
        <li>
          <a href="#recommend" data-toggle="tab" value="recommend"
            id="tab-recommend">
            <%= t ".recommend" %>
          </a>
        </li>
        <% Blog.categories.values.each do |category| %>
          <li>
            <a href="#tab<%= category %>" data-toggle="tab" value="<%= category %>"
              class="category-tab" id="tab-<%= category %>">
              <%= t ".category#{category}" %>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="tab-bar-bottom"></div>
    </div>
  </div>
</div>
<div class="tab-content">
  <div id="home" class="tab-pane in active">
    <div class="user-blog-list">
      <div id="my-blogs">
        <%= render "blogs" %>
        <div id="infinite-scrolling">
          <%= paginate @blogs, theme: "twitter-bootstrap-3" %>
        </div>
      </div>
    </div>
  </div>
  <div id="recommend" class="tab-pane">
    <div class="user-blog-recommend">
    </div>
  </div>
  <% Blog.categories.values.each do |category| %>
    <div id="tab<%= category %>" class="tab-pane user-blog-list">
    </div>
  <% end %>
</div>
<div class="tab-bar-index">
  <%= render "tab_bar" %>
</div>
<%= render "modal" if present_modal %>

app/views/blogs/index.js.erb
$('#my-blogs').append('<%= j render "blogs" %>');
<% if @blogs.next_page %>
  $('.pagination').replaceWith('<%= j paginate @blogs %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/blogs/show.html.erb
<div class="show-blog-form">
  <div class="author-header">
    <p class="author-header-title"><%= "なるほどブログ" %></p>
  </div>
  <% if @blog.is_recommend? %>
    <%= image_tag "commend.png", size: Settings.blog.recommend_icon %>
    <div class="row1 blog-recommend">
      <%= render "blog_list", blog: @blog %>
    </div>
  <% else %>
    <div class="row1">
      <%= render "blog_list", blog: @blog %>
    </div>
  <% end %>
  <div class="content-show">
    <%= render "social_share_button", blog: @blog %>
    <div class="blog-content">
      <%= image_tag @blog.image, id: "img-thumbnail" %>
      <div class="blog-body-show">
        <%= @blog.body.html_safe %>
      </div>
    </div>
    <div class="blog-author-show">
      <%= image_tag "show-author.png", class: "show-header" %>
      <%= link_to image_tag("author-details-show.png"), 'javascript:void(0)',
        class: "author-details-button", id: "#{@blog.id}" %>
    </div>
  </div>
  <%= render "react", react: @react, blog: @blog %>
  <div class="content-show">
    <div class="social-share-button">
      <div class="sns-div">
        <%= image_tag "SNS.png", class: "sns-image" %>
      </div>
      <%= render "social_share_button", blog: @blog %>
    </div>
  </div>
</div>
<div class="show-author">
</div>
<div class="tab-bar-index">
  <%= render "tab_bar" %>
</div>