config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins, path: 'admins'
  devise_for :users, path: 'users', controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'blogs#index'

  namespace :admin do
    resources :blogs
    get '/', to: 'blogs#home'
  end

  resources :blogs, only: [:show, :index]
  resources :users, only: [:show, :update, :edit]
  resources :reacts, only: :create
  delete 'reacts', to: 'reacts#destroy'
  patch 'reacts', to: 'reacts#update'
  get 'messages/index'
  get 'blogs/:id/:token', to: 'blogs#show', as: 'token_blog'
  get 'app_author', to: 'blogs#app_author'
end

app/views/admins/shared/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>