config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins, path: 'admins'
  devise_for :users, path: 'users', controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'blogs#index'

  namespace :admin do
    resources :blogs
    get '/', to: 'blogs#home'
  end

  resources :blogs, only: [:show, :index]
  resources :users, only: [:show, :update, :edit]
  resources :reacts, only: :create
  delete 'reacts', to: 'reacts#destroy'
  patch 'reacts', to: 'reacts#update'
  get 'messages/index'
  get 'blogs/:id/:token', to: 'blogs#show', as: 'token_blog'
  get 'app_author', to: 'blogs#app_author'
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :reacts, dependent: :destroy
  enum category: %w[family school study]

  mount_uploader :image, ImageUploader
  mount_uploader :author_picture, AuthorPictureUploader

  ATTR_PARAMS = [
    :title,
    :category,
    :public_time,
    :is_public,
    :is_recommend,
    :image,
    :body,
    :author_name,
    :author_position,
    :author_age,
    :author_picture
  ].freeze

  validates :title, presence: true, length: { maximum: 255 }
  validates :category, presence: true
  validates :public_time, presence: true
  validates :body, presence: true
  validates :image, presence: true
  validates :author_name, presence: true
  validates :author_position, presence: true
  validates :author_age, presence: true
  validates :author_picture, presence: true

  validate :validate_image_size
  validate :validate_author_age

  scope :sort_blog, ->(param_sort) { order public_time: param_sort }
  scope :public_blogs, lambda {
    where 'is_public = ? AND public_time < ?', true, Time.zone.now
  }
  scope :recommend_blogs, -> { where 'is_recommend = ?', true }
  scope :blog_by_category, ->(category) { where 'category = ?', category }

  class << self
    def new_token
      chars = (0..9).to_a + ('a'..'z').to_a + ('A'..'Z').to_a
      chars.sample(16).join
    end
  end

  private

  def validate_image_size
    return unless image.size > Settings.image.max_capacity.megabytes
    errors.add :image,
               I18n.t('error_capacity_image',
                      maximum: Settings.image.max_capacity)
  end

  def validate_author_age
    return errors.add I18n.t('error_age') if author_age < 0
  end
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  before_action :authenticate_admin!
  before_action :load_blog, only: [:update, :edit]
  before_action :load_blogs, only: :index

  def index
    respond_to do |format|
      if request.xhr?
        sort_blog
        format.html do
          render partial: 'sort_blog',
                 locals: { sort_blogs: @sort_blogs }
        end
      end
      format.html
    end
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new create_blog_params
    default_author_picture if @blog.author_picture.blank?
    if @blog.save
      flash[:success] = t '.saved'
      redirect_to admin_blogs_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if request.xhr?
      render json: @blog.is_public
      update_params
    else
      update_blog
    end
  end

  def home; end

  private

  def load_blogs
    @search = Blog.ransack params[:q]
    @blogs = @search.result.order(created_at: :desc).page(params[:page])
                    .per Settings.list_blog
  end

  def sort_blog
    params[:sort] ||= :DESC
    @sort_blogs = Blog.sort_blog(params[:sort]).page(params[:page])
                      .per Settings.list_blog
  end

  def update_params
    if params[:public_time].present?
      @blog.update_attributes public_time: params[:public_time]
    elsif params[:is_public].present?
      @blog.update_attributes is_public: params[:is_public]
    end
  end

  def blog_params
    params.require(:blog).permit Blog::ATTR_PARAMS
  end

  def create_blog_params
    blog_params.merge! token: Blog.new_token
  end

  def update_blog
    if @blog.update_attributes blog_params
      flash[:success] = t '.updated'
      redirect_to admin_blogs_path
    else
      render :edit
    end
  end

  def load_blog
    @blog = Blog.find_by id: params[:id]
  end

  def default_author_picture
    path = File.join(Rails.root, 'app/assets/images/', Settings.author.image)
    File.open(path) do |f|
      @blog.author_picture = f
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :check_token, only: :show
  before_action :load_react, only: [:show, :index]

  def index
    @blogs = Blog.public_blogs.order(public_time: :desc).page(params[:page]).per 5
    @recommend_blogs = Blog.recommend_blogs.order(public_time: :desc).page(params[:page]).per 5
    @category_blogs = Blog.blog_by_category(params[:category_type])
                          .order(public_time: :desc).page(params[:page]).per 5
    respond_to do |format|
      format.html
      format.js
      return unless request.xhr?
      format.json { data_json }
    end
  end

  def show
    respond_to do |format|
      if request.xhr?
        format.html do
          render partial: 'author',
                 locals: { blog: @blog }
        end
      end
      format.html
    end
  end

  def app_author; end

  private

  def load_react
    @react = if current_user.present?
               React.find_by_user_id_and_blog_id(current_user.id, params[:id])
             else
               React.find_by_code_and_blog_id(cookies[:guest_token], params[:id])
             end
  end

  def data_json
    render json: {
      category_blogs: render_to_string(
        partial: 'blogs/category_blogs',
        locals: { category_blogs: @category_blogs },
        formats: 'html',
        layout: false
      ),
      recommend_blogs: render_to_string(
        partial: 'blogs/recommend_blogs',
        locals: { recommend_blogs: @recommend_blogs },
        formats: 'html',
        layout: false
      )
    }
  end

  def check_token
    if params[:token].present?
      @blog = Blog.find_by(token: params[:token], id: params[:id])
    else
      authenticate_user!
      @blog = Blog.find_by id: params[:id]
    end
  end
end

app/views/admin/blogs/_form.html.erb
<div class="form-blog">
  <div id="blog-form">
    <%= form_for [:admin, @blog] do |f| %>
      <%= render "shared/error_message", object: f.object %>
      <div class="row">
        <div class="col-md-2">
          <%= f.label :title, t(".title"), class: "label-form" %>
        </div>
        <div class="col-md-10">
          <%= f.text_field :title, class: "blog-title form-control" %>
          <div id="title-confirm" class="confirm-blog"></div>
          <div id="title-error" class="error-message"></div>
        </div>
      </div></br>

      <div class="row">
        <div class="col-md-2">
          <%= f.label :category, t(".category"), class: "label-form" %>
        </div>
        <div class="col-md-2">
          <%= f.select :category, Blog.categories.keys.map{ |c| [t(".#{c}"), c] },
            {selected: @blog.category, include_blank: true},
            {class: "form-control category-blog"} %>
          <div id="category-confirm" class="confirm-blog"></div>
          <div id="category-error" class="error-message"></div>
        </div>
      </div></br>

      <div class="row">
        <div class="col-md-2">
          <%= f.label :public_time, t(".public_time"), class: "label-form" %>
        </div>
        <div class="col-md-3">
          <%= f.text_field :public_time, class: "datetimepicker form-control",
            value: format_time(@blog.public_time, :format_date),
            id: "blog-time" %>
          <div id="public-time-confirm" class="confirm-blog"></div>
          <div id="public-time-error" class="error-message"></div>
        </div>
      </div></br>

      <div class="row">
        <div class="col-md-2">
          <%= f.label :is_public, t(".public"), class: "label-form" %>
        </div>
        <div class="col-md-10 is-public">
          <%= f.check_box :is_public %>
          <div class="is-public-confirm"></div>
        </div>
      </div></br>

      <div class="row">
        <div class="col-md-2">
          <%= f.label :is_recommend, t(".recommend"), class: "label-form" %>
        </div>
        <div class="col-md-10 is-recomend">
          <%= f.check_box :is_recommend %>
          <div class="is-recommend-confirm"></div>
        </div>
      </div></br>

      <div class="row">
        <div class="col-md-2">
          <%= f.label :image, t(".image"), class: "label-form" %>
        </div>
        <div class="col-md-10">
          <% if @blog.image? %>
            <%= image_tag @blog.image, size: Settings.avatar_create_size,
              id: "image-view" %>
          <% else %>
            <%= image_tag Settings.default_blog_image, id: "image-view",
              class: "image-create", size: Settings.avatar_create_size %>
          <% end %></br>
          <div class="input-image">
            <h4><%= t ".image_require" %></h4>
            <div>
              <label for="blog_image" class="btn btn-default">
                <%= t ".open" %>
              </label>
              <%= f.file_field :image, accept: Settings.image.image_format_accept,
                class: "upload-image" %>
            </div></br>
          </div>
          <div id="image-error" class="error-message"></div>
        </div>
      </div></br>

      <div class="row">
        <div class="col-md-2">
          <%= f.label :body, t(".body"), class: "label-form" %>
        </div>
        <div class="col-md-10">
          <div class="preview">
            <%= link_to t(".preview"), "javascript:void(0)", class: "preview-btn" %>
          </div>
          <div class="body-input">
            <%= f.text_area :body, class: "ckeditor" %>
          </div>
          <div class="body-confirm hidden-input"></div>
          <div id="body-error" class="error-message"></div>
        </div>
      </div></br>

      <h2><%= t ".setting_for_author" %></h2>
      <div class="setting-author">
        <div class="row">
          <div class="col-md-2">
            <%= f.label :author_name, t(".author_name"), class: "label-form" %>
          </div>
          <div class="col-md-4">
            <%= f.text_field :author_name, class: "blog-author-name form-control" %>
            <div id="author-name-confirm" class="confirm-blog"></div>
            <div id="author-name-error" class="error-message"></div>
          </div>
        </div></br>

        <div class="row">
          <div class="col-md-2">
            <%= f.label :author_position, t(".author_position"),
              class: "label-form" %>
          </div>
          <div class="col-md-4">
            <%= f.text_field :author_position,
              class: "blog-author-position form-control" %>
            <div id="author-position-confirm" class="confirm-blog"></div>
            <div id="author-position-error" class="error-message"></div>
          </div>
        </div></br>

        <div class="row">
          <div class="col-md-2">
            <%= f.label :author_age, t(".author_age"), class: "label-form" %>
          </div>
          <div class="col-md-4">
            <%= f.number_field :author_age, class: "blog-author-age form-control" %>
            <div id="author-age-confirm" class="confirm-blog"></div>
            <div id="author-age-error" class="error-message"></div>
          </div>
        </div></br>

        <div class="row">
          <div class="col-md-2">
            <%= f.label :author_picture, t(".author_picture"),
              class: "label-form" %>
          </div>
          <div class="col-md-4">
            <% if @blog.author_picture? %>
              <%= image_tag @blog.author_picture, id: "picture-view",
                size: Settings.avatar_create_size %>
            <% else %>
              <%= image_tag Settings.author.image, id: "picture-view",
                size: Settings.avatar_create_size %>
            <% end %>
            <div class="input-image">
              <h4><%= t ".image_require" %></h4>
              <div>
                <label for="blog_author_picture" class="btn btn-default">
                  <%= t ".open" %>
                </label>
                <%= f.file_field :author_picture,
                  accept: Settings.image.image_format_accept,
                  class: "upload-picture" %>
              </div>
            </div>
            <div id="author-picture-error" class="error-message"></div>
          </div>
        </div></br>
      </div>
      <%= button_tag t(".confirm"), class: "save-after-confirm hidden-input" %>
    <% end %>
    <div class="row">
      <div class="confirm-list-button">
        <div class="col-md-4 col-md-offset-5">
          <div class="col-md-4">
            <%= link_to t(".list"), admin_blogs_path, data: {turbolinks: false},
              class: "btn btn-default form-control" %>
          </div>
          <div class="col-md-4 col-md-offset-1">
            <%= button_tag t(".confirm"),
              class: "btn btn-primary confirm-blog form-control" %>
          </div>
        </div>
      </div>
      <div id="save-button" class="hidden-input">
        <div class="col-md-4 col-md-offset-5">
          <div class="col-md-4">
            <%= button_tag t(".cancel"), data: {turbolinks: false},
              class: "btn btn-default cancel-confirm form-control" %>
          </div>
          <div class="col-md-4 col-md-offset-1">
            <%= button_tag t(".save"),
              class: "btn btn-primary save-blog form-control" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="preview-content" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= t ".body" %></h4>
      </div>
      <div class="modal-body" id="modal-content">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default"
          data-dismiss="modal"><%= t ".close" %></button>
      </div>
    </div>
  </div>
</div>

app/views/admin/blogs/_sort_blog.html.erb
<%= render "tbody_list_blog", list: @sort_blogs %>
<div class="kaminari">
  <%= paginate @sort_blogs, theme: "twitter-bootstrap-3" %>
</div>

app/views/admin/blogs/_tbody_list_blog.html.erb
<% list.each_with_index do |blog, index| %>
  <tr>
    <td><%= blog.id %></td>
    <td>
      <%= format_time(blog.created_at, :format_datetime) %>
    </td>
    <td class="td-title"><%= blog.title %></td>
    <td><%= t(".#{blog.category}") %></td>
    <td>
      <% if blog.is_recommend? %>
        <%= image_tag "recommend-icon.png", size: "20x20" %>
      <% end %>
    </td>
    <td><%= blog.author_name  %></td>
    <td>
      <% if blog.image.present? %>
        <%= image_tag blog.image, size: Settings.size_image_thumbnail %>
      <% else %>
        <%= image_tag Settings.default_blog_image,
          size: Settings.size_image_thumbnail %>
      <% end %>
    </td>
    <td id="blog<%= blog.id %>">
      <% if blog.is_public? && (blog.public_time < Time.zone.now) %>
        <%= t ".public" %>
      <% else %>
        <%= t ".unpublic" %>
      <% end %>
    </td>
    <td>
      <div class="public-time<%= blog.id %>">
        <%= format_time(blog.public_time, :format_datetime) %>
      </div>
      <div class="hidden-input" id="change-time<%= blog.id %>">
        <input class="form-control" id="setting-time<%= blog.id %>"
          value="<%= format_time(blog.public_time, :format_datetime) %>">
      </div></br>
      <%= button_tag t(".change_public_time"), id: "#{blog.id}",
        class: "btn btn-default setting-time" %>
      <% if blog.is_public? && (blog.public_time < Time.zone.now) %>
        <%= button_tag t(".stop"), id: "blog-#{blog.id}",
          class: "btn btn-danger setting-public hidden-input",
          value: "#{blog.id}" %>
      <% end %>
    </td>
    <td><%= link_to t(".edit"), edit_admin_blog_path(blog),
      class: "btn btn-default", data: {turbolinks: false} %></td>
  </tr>
<% end %>

app/views/admin/blogs/edit.html.erb
<%= render "layouts/header" %>
  <div id="yield">
  <%= render "form" %>
</div>

app/views/admin/blogs/home.html.erb
<%= render "layouts/header" %>
<%= render "layouts/flash" %>
<div class="col col-md-3 col-md-offset-2 home-admin">
  <h1><%= t ".blog" %></h1>
  <li><%= link_to t(".list"), admin_blogs_path %></li>
  <li><%= link_to t(".create"), new_admin_blog_path %></li>
</div>

app/views/admin/blogs/index.html.erb
<%= render "layouts/header" %>
<div id="yield">
  <%= render "layouts/flash" %>
  <div class="row">
    <div class="search-form">
      <h2><%= t ".search_filter" %></h2>
      <hr class="divider"></hr>
      <%= search_form_for [:admin, @search ] do |f| %>
        <div class="row">
          <div class="col-md-3">
            <%= f.label :title, t(".title") %>
            <%= f.text_field :title_cont, class: "form-control" %>
          </div>
          <div class="col-md-2">
            <%= f.label :category, t(".category") %>
            <%= f.select :category_eq,
              options_for_select(Blog.categories.map{ |c|  [ t(".#{c[0]}"), c[1] ] },
              @search.category_eq), {include_blank: true}, class: "form-control" %>
          </div>
          <div class="col-md-2">
            <%= f.label :is_public, t(".is_public") %>
            <%= f.select :is_public_eq,
              options_for_select([[t(".public"), true], [t(".unpublic"), false]]),
              {include_blank: true}, class: "form-control" %>
          </div>
           <div class="col-md-2">
            <%= f.label :is_recommend, t(".recommend") %>
            <%= f.select :is_recommend_eq,
              options_for_select([[t(".recommend"), true], [t(".unrecommend"), false]]),
              {include_blank: true}, class: "form-control" %>
          </div>
          <div class="col-md-2">
            <label><%= t ".sort" %></label>
            <select id="sort-blog" class="form-control">
              <option value></option>
              <option value="asc"><%= t ".ascrease" %></option>
              <option value="desc"><%= t ".descrease" %></option>
            </select>
          </div>
          <div class="button-search col-md-1"></br>
            <%= f.submit t(".search"), class: "btn btn-default form-control" %>
          </div>
        </div>
      <% end %>
    </div></br>
    <div class="create-button">
      <%= link_to t(".create_new_blog"), new_admin_blog_path,
        class: "btn btn-primary", id: "create-new-blog",
        data:{turbolinks: false} %>
    </div>
    <div class="kaminari">
      <%= paginate @blogs, theme: "twitter-bootstrap-3" %>
    </div>
    <table class="table table-hover" id="list-table">
      <thead>
        <tr>
          <th><%= t ".id" %></th>
          <th><%= t ".create_time" %></th>
          <th><%= t ".title" %></th>
          <th><%= t ".category" %></th>
          <th><%= t ".recommend" %></th>
          <th><%= t ".author" %></th>
          <th><%= t ".image" %></th>
          <th><%= t ".is_public" %></th>
          <th><%= t ".public_time" %></th>
          <th><%= t ".action" %></th>
        </tr>
      </thead>
      <tbody class="list-blogs">
        <%= render "tbody_list_blog", list: @blogs %>
      </tbody>
    </table>
    <div class="kaminari">
      <%= paginate @blogs, theme: "twitter-bootstrap-3" %>
    </div>
  </div>
</div>

app/views/admin/blogs/new.html.erb
<%= render "layouts/header" %>
<div id="yield">
  <h1><%= t ".create_blog" %></h1>
  <%= render "form" %>
</div>