config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins, path: 'admins'
  devise_for :users, path: 'users', controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'blogs#index'

  namespace :admin do
    resources :blogs
    get '/', to: 'blogs#home'
  end

  resources :blogs, only: [:show, :index]
  resources :users, only: [:show, :update, :edit]
  resources :reacts, only: :create
  delete 'reacts', to: 'reacts#destroy'
  patch 'reacts', to: 'reacts#update'
  get 'messages/index'
  get 'blogs/:id/:token', to: 'blogs#show', as: 'token_blog'
  get 'app_author', to: 'blogs#app_author'
end

app/views/layouts/_flash.html.erb
<div class="row">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> fade in hide-flash col-md-3"
      id="flash-message" >
      <a class="close" data-dismiss="alert" href="#" aria-hidden="true">
        &times;
      </a>
      <%= message %>
    </div>
  <% end %>
</div></br>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" id="menu">
  <div class="container">
    <ul class="nav navbar-nav">
      <li class="<%= active_class(admin_path) %>">
        <%= link_to t(".home"), admin_path, data: {turbolinks: false} %>
      </li>
      <li class="<%= active_class(admin_blogs_path) %> <%= active_class(new_admin_blog_path) %>">
        <a href="<%= admin_blogs_path %>" data-turbolinks="false">
          <%= t ".blogs" %>
        </a>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">
          <%= t ".blog" %>
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="<%= admin_blogs_path %>"><%= t ".list" %></a></li>
          <li><a href="<%= new_admin_blog_path %>">
            <%= t ".creat" %>
          </a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to t(".logout"),
        destroy_admin_session_path, method: :delete %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_present.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner" id="slide-item">
    <div class="item active">
      <%= image_tag Settings.present1, class: "image-item" %>
    </div>

    <div class="item">
      <%= image_tag Settings.present2, class: "image-item" %>
    </div>

    <div class="item">
      <%= image_tag Settings.present3, class: "image-item" %>
    </div>
  </div>

  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="buttons-wrapper">
  <div>
    <span>
      <%= "Let's join with us to get more" %>
    </span></br>
  </div></br>
  <div>
    <a class="btn login-btn">
      <%= t "layouts.header.login" %>
    </a>
    <a class="btn" href="<%= blogs_path %>">
      <%= "list blog" %>
    </a>
  </div>
</div>

<%= render "devise/sessions/form_login" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ems</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
      'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    </header>
    <container>
      <%= yield %>
    </container>
  </body>
</html>